name: Build and Push Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    - run: |
        docker build -t your-dockerhub/ai-api:${{ github.sha }} .
        docker push your-dockerhub/ai-api:${{ github.sha }}
