image:
  repository: REPLACE_WITH_ECR_OR_DOCKER_REPO # e.g., 1234567890.dkr.ecr.ap-south-1.amazonaws.com/cicd-demo
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources: {}

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: demo.local
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
