apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cicd-demo.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "cicd-demo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cicd-demo.name" . }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
