apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dev
  labels:
    app: hello-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-dev
  template:
    metadata:
      labels:
        app: hello-dev
    spec:
      containers:
      - name: hello
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80