apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-staging
  labels:
    app: hello-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-staging
  template:
    metadata:
      labels:
        app: hello-staging
    spec:
      containers:
      - name: hello
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80