apiVersion: v1
kind: Service
metadata:
  name: hello-prod
  labels:
    app: hello-prod
spec:
  type: ClusterIP
  selector:
    app: hello-prod
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http